---
- - :approve
  - memfs
  - :who:
    :why: The Unlicense
    :versions: []
    :when: 2025-11-10 07:51:08.684228900 Z
- - :approve
  - fs-monkey
  - :who:
    :why: The Unlicense
    :versions: []
    :when: 2025-11-10 07:51:18.740633200 Z
- - :approve
  - big-integer
  - :who:
    :why: The Unlicense
    :versions: []
    :when: 2025-11-10 07:51:30.358974200 Z
- - :approve
  - "@pipedrive/app-extensions-sdk"
  - :who:
    :why: MIT
    :versions: []
    :when: 2025-11-10 07:52:01.050944100 Z
