namespace: "pipedrive"
name: "callback"
version: 0
address: ":5454"
repl_address: ":3132"
debug: false
registry:
  addresses: [""]
  type: 2
tracer:
  enable: false
  address: ""
  type: 1
resilience:
  rate_limiter:
    limit: 1000
    iplimit: 100
  circuit_breaker:
    timeout: 2500
logger:
  name: "callback-logger"
  level: 1
  color: true
credentials:
  client_id: ""
  client_secret: ""
  redirect_url: ""
onlyoffice:
  builder:
    document_server_url: ""
    document_server_secret: ""
    document_server_header: ""
    gateway_url: ""
    callback_url: ""
  callback:
    max_size: 210000000000
    upload_timeout: 120
