namespace: "pipedrive"
name: "builder"
version: 0
address: ":6260"
repl_address: ":7979"
debug: false
registry:
  addresses: [""]
  type: 2
tracer:
  enable: false
  address: ""
  type: 1
resilience:
  rate_limiter:
    limit: 500
  circuit_breaker:
    timeout: 2500
logger:
  name: "builder-logger"
  level: 1
  color: true
credentials:
  client_id: ""
  client_secret: ""
  redirect_url: ""
onlyoffice:
  builder:
    document_server_url: ""
    document_server_secret: ""
    document_server_header: ""
    gateway_url: ""
    callback_url: ""