namespace: "pipedrive"
name: "gateway"
version: 0
address: ":6044"
repl_address: ":9999"
debug: false
registry:
  addresses: [""]
  type: 2
tracer:
  enable: false
  address: ""
  type: 1
resilience:
  rate_limiter:
    limit: 1000
    iplimit: 100
  circuit_breaker:
    timeout: 15000
logger:
  name: "gateway-logger"
  level: 1
  color: true
credentials:
  client_id: ""
  client_secret: ""
  redirect_url: ""
onlyoffice:
  builder:
    allowed_downloads: 10