namespace: "pipedrive"
name: "auth"
version: 0
address: ":5052"
repl_address: ":5053"
debug: false
persistence:
  url: ""
registry:
  addresses: ["127.0.0.1:8500"]
  type: 2
messaging:
  type: 1
  addresses: ["0.0.0.0:5672"]
  durable: true
  ack_on_success: true
  requeue_on_error: true
  disable_auto_ack: true
tracer:
  enable: false
  address: "http://127.0.0.1:9411/api/v2/spans"
  type: 1
resilience:
  rate_limiter:
    limit: 500
  circuit_breaker:
    timeout: 2500
logger:
  name: "auth-logger"
  level: 1
  color: true
oauth:
  client_id: ""
  client_secret: ""
