name: "Build onlyoffice-pipedrive"

run-name: "Build onlyoffice-pipedrive: ${{ github.event.inputs.tag || github.run_number }}"

on:
  push:
    branches:
    - develop
    paths-ignore:
    - '.github/**'

  workflow_dispatch:
    inputs:
      tag:
        description: 'Specify tag (ex. rc.5) or it will be set automaticaly :rc.<run_number>'
        type: string
        required: false
      create_modal_id:
        description: 'If set, overwrite create-modal-id with value that you specify'
        type: string
        required: false
      backend_gateway:
        description: 'If set, overwrite backend_gateway with value that you specify'
        type: string
        required: false
      type:
        type: choice
        description: For which environment should substitute arguments?
        options:
        - 'prod'
        - 'dev'

env:
  DOCKER_HUB_NAMESPACE: onlyoffice

jobs:
  build:
    name: "Build ${{ matrix.service}}: ${{ github.event.inputs.tag || github.run_number }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ frontend, settings, gateway, auth, builder, callback ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Mask custom value
        if: github.event.inputs.create_modal_id != ''
        id: mask-value
        run: |
          MODAL_ID=$(jq -r '.inputs.create_modal_id' $GITHUB_EVENT_PATH)
          echo ::add-mask::${MODAL_ID}
          echo "CUSTOM_MODAL_ID=${MODAL_ID}" >> "$GITHUB_ENV"

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Handle tag
        env:
          EVENT: ${{ github.event_name }}
          REF: ${{ github.ref_name }}
          MANUAL_TAG: ${{ github.event.inputs.tag }}
        run: |
          echo "APP_VERSION=$(cat frontend/package.json | jq -r '.version')" >> "$GITHUB_ENV"

          if [[ "$EVENT" == 'push' && "$REF" == 'develop' ]]; then
           echo "RC_TAG=rc.${{ github.run_number }}" >> "$GITHUB_ENV"
          elif [[ "$EVENT" == 'workflow_dispatch' && -z "$TAG" ]]; then
           echo "RC_TAG=rc.${{ github.run_number }}" >> "$GITHUB_ENV"
          fi

      - name: Handle build arguments
        shell: bash
        env: 
          ARG_POSTFIX: ${{ (github.event_name == 'push' && 'dev') || github.event.inputs.type }}
          CUSTOM_BACKEND_GATEWAY: ${{ github.event.inputs.backend_gateway }}
        run: |
          declare -A ArgsArray=( 
                     [backend_gateway_prod]=https://pipedrive-gateway.onlyoffice.com
                     [backend_gateway_dev]=https://pipedrive-gateway.teamlab.info
                     [create_modal_id_prod]=${{ secrets.CREATE_MODAL_ID_PROD }}
                     [create_modal_id_dev]=${{ secrets.CREATE_MODAL_ID_DEV }}
                     )
          
          echo "BACKEND_GATEWAY=${CUSTOM_BACKEND_GATEWAY:-${ArgsArray[backend_gateway_${ARG_POSTFIX}]}}" >> "$GITHUB_ENV"
          echo "PIPEDRIVE_CREATE_MODAL_ID=${CUSTOM_MODAL_ID:-${ArgsArray[create_modal_id_${ARG_POSTFIX}]}}" >> "$GITHUB_ENV"

      - name: Publish Image
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_RECORD_UPLOAD: false
        with:
          build-args: |
                  BACKEND_GATEWAY=${{ env.BACKEND_GATEWAY}}
                  PIPEDRIVE_CREATE_MODAL_ID=${{ env.PIPEDRIVE_CREATE_MODAL_ID }}
          target: ${{ matrix.service }}
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ env.DOCKER_HUB_NAMESPACE }}/pipedrive-${{ matrix.service }}:${{ env.APP_VERSION }}-${{ github.event.inputs.tag || env.RC_TAG }}
